spring:
  zipkin:
    base-url: http://localhost:9411/


hazelcast:
  network:
  join:
  multicast:
  enabled: true

management:
  tracing:
    sampling:
      probability: 1
 This property must be added in application.yml file, in order to see logs in zipkin
